<a href="https://colab.research.google.com/github/IIAnirudhII/BU/blob/master/Deep%20Learning/Lab1/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# Random Integers
s1=np.random.randint(-100,100,size=(10))
print(s1)
print("Dimension = ",s1.ndim)

[ 49  32  17 -45  63 -45 -61 -96 -95 -31]
Dimension =  1


In [ ]:
# Random floats
s2=np.random.sample(size=10)
print(s2)
print("Dimension = ",s2.ndim)

[0.16204166 0.33115718 0.36746588 0.79380819 0.22923692 0.31561973
 0.04454992 0.96244014 0.7489887  0.0236809 ]
Dimension =  1


In [ ]:
# Random complex numbers
s3 = np.random.random(10) + np.random.random(10) * 1j
print(s3)
print("Dimension = ",s3.ndim)

[0.20748243+0.67336116j 0.15120986+0.47220665j 0.83211899+0.28309576j
 0.31382601+0.8864533j  0.01778966+0.08986296j 0.55026769+0.21597136j
 0.71358953+0.47915104j 0.17032774+0.42707006j 0.4874435 +0.20726309j
 0.23610296+0.38006096j]
Dimension =  1


In [ ]:
s=np.vstack((s1,s2,s3))
print(s)
print("Dimension = ",s.ndim)

[[ 4.90000000e+01+0.j          3.20000000e+01+0.j
   1.70000000e+01+0.j         -4.50000000e+01+0.j
   6.30000000e+01+0.j         -4.50000000e+01+0.j
  -6.10000000e+01+0.j         -9.60000000e+01+0.j
  -9.50000000e+01+0.j         -3.10000000e+01+0.j        ]
 [ 1.62041664e-01+0.j          3.31157185e-01+0.j
   3.67465881e-01+0.j          7.93808185e-01+0.j
   2.29236921e-01+0.j          3.15619725e-01+0.j
   4.45499160e-02+0.j          9.62440145e-01+0.j
   7.48988703e-01+0.j          2.36809024e-02+0.j        ]
 [ 2.07482426e-01+0.67336116j  1.51209861e-01+0.47220665j
   8.32118993e-01+0.28309576j  3.13826013e-01+0.8864533j
   1.77896561e-02+0.08986296j  5.50267692e-01+0.21597136j
   7.13589530e-01+0.47915104j  1.70327739e-01+0.42707006j
   4.87443497e-01+0.20726309j  2.36102956e-01+0.38006096j]]
Dimension =  2


In [ ]:
m1=np.matrix('1 2 3;4 5 6;7 8 9')

m2=np.matrix('4 5 6;7 8 9;1 2 3')

In [ ]:
# Addition of two matrices
add=m1+m2
print(add)

[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]


In [ ]:
# Transpose

m1.T

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [ ]:
# Dot product
dot=np.dot(m1,m2)
print(dot)

[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


In [ ]:
# Multiplication
np.multiply(m1,m2)

matrix([[ 4, 10, 18],
        [28, 40, 54],
        [ 7, 16, 27]])

In [ ]:
# Access matrix elements
A=[[1,2,3,4],[4,5,6,7],[8,9,0,7]]
print("A= ",A)
print("1st row: ",A[0])
print("Element from 2nd row 3rd column: ",A[1][2])
Ac=np.array(A)
print("2nd column: ",Ac[:,1])

A=  [[1, 2, 3, 4], [4, 5, 6, 7], [8, 9, 0, 7]]
1st row:  [1, 2, 3, 4]
Element from 2nd row 3rd column:  6
2nd column:  [2 5 9]


In [29]:
arr=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,20,]

#Slicing
print(arr[2:5])

#reversing array
print(arr[::-1])

[3, 4, 5]
[20, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [ ]:
df=pd.read_excel('https://github.com/IIAnirudhII/BU/blob/master/Deep%20Learning/Lab2/data/Online%20Retail.xlsx?raw=true')
df=df[:100]

In [ ]:
arr=df.to_numpy()
arr

array([[536365, '85123A', 'WHITE HANGING HEART T-LIGHT HOLDER', 6,
        Timestamp('2010-12-01 08:26:00'), 2.55, 17850.0,
        'United Kingdom'],
       [536365, 71053, 'WHITE METAL LANTERN', 6,
        Timestamp('2010-12-01 08:26:00'), 3.39, 17850.0,
        'United Kingdom'],
       [536365, '84406B', 'CREAM CUPID HEARTS COAT HANGER', 8,
        Timestamp('2010-12-01 08:26:00'), 2.75, 17850.0,
        'United Kingdom'],
       [536365, '84029G', 'KNITTED UNION FLAG HOT WATER BOTTLE', 6,
        Timestamp('2010-12-01 08:26:00'), 3.39, 17850.0,
        'United Kingdom'],
       [536365, '84029E', 'RED WOOLLY HOTTIE WHITE HEART.', 6,
        Timestamp('2010-12-01 08:26:00'), 3.39, 17850.0,
        'United Kingdom'],
       [536365, 22752, 'SET 7 BABUSHKA NESTING BOXES', 2,
        Timestamp('2010-12-01 08:26:00'), 7.65, 17850.0,
        'United Kingdom'],
       [536365, 21730, 'GLASS STAR FROSTED T-LIGHT HOLDER', 6,
        Timestamp('2010-12-01 08:26:00'), 4.25, 17850.0,
        