<a href="https://colab.research.google.com/github/IIAnirudhII/BU/blob/master/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import numpy as np
import pandas as pd

In [15]:
# Random Integers
s1=np.random.randint(-100,100,size=(100))
print(s1)
print("Shape = ",s1.shape)

[ 88  66  65 -88 -72  89  38 -45  95  45 -78 -88  52 -13   0  40  51  50
  96 -93  82 -34 -78 -75 -80  -5  20 -61  97  90  41 -68  92 -61 -54  96
  57  24 -68  61 -38  27 -53 -90  10 -12  23  79   8 -64 -51  94 -94 -61
  82 -89   5 -39  89  35 -88 -84 -67  39  23   4 -97  33  27  48 -68  12
  97  87 -85  85  78 -40 -65 -62  11  10 -84  -5 -60 -91  62 -24 -54   9
 -41 -43 -50   1 -21  67  59  57  75  79]
Shape =  (100,)


In [16]:
# Random floats
s2=np.random.sample(size=100)
print(s2)
print("Shape = ",s2.shape)

[0.74527603 0.63540074 0.65718454 0.66795748 0.45129043 0.79475315
 0.04310505 0.65521525 0.58384001 0.23633706 0.37007986 0.99668799
 0.29797365 0.90363849 0.184878   0.53899071 0.93108336 0.42543499
 0.4583842  0.76224791 0.61414556 0.43928591 0.70470664 0.45597392
 0.35690841 0.12480789 0.90664534 0.1560435  0.71062864 0.63398653
 0.97595579 0.73440798 0.2208977  0.77742723 0.68370569 0.19502521
 0.9018712  0.23419622 0.73876702 0.96125243 0.63350508 0.64189571
 0.64848217 0.80884988 0.80180668 0.91660149 0.29059019 0.83104562
 0.84027124 0.92969974 0.01669623 0.35718101 0.6807605  0.40248162
 0.31710825 0.96606768 0.0081279  0.18183518 0.68654158 0.28650696
 0.79918544 0.60715152 0.71068097 0.99577178 0.2365361  0.94477328
 0.21535413 0.64927931 0.9234632  0.02084316 0.03404251 0.90375847
 0.50663577 0.84224362 0.14005445 0.58912067 0.98167933 0.40913793
 0.77264129 0.26608057 0.79997355 0.00119685 0.96293359 0.47094733
 0.26923038 0.36663034 0.80080214 0.43349127 0.41599123 0.5767

In [17]:
# Random complex numbers
s3 = np.random.random(10) + np.random.random(10) * 1j
print(s3)
print("Shape = ",s3.shape)

[0.3478964 +0.95875698j 0.58087428+0.62516648j 0.11692595+0.75622546j
 0.79413337+0.69110637j 0.37611687+0.16706963j 0.07879582+0.75829237j
 0.33998448+0.67830325j 0.47229835+0.22032617j 0.42311086+0.28453627j
 0.42822072+0.25431962j]
Shape =  (10,)


In [20]:
m1=np.matrix('1 2 3;4 5 6;7 8 9')

m2=np.matrix('4 5 6;7 8 9;1 2 3')

In [21]:
# Addition of two matrices
add=m1+m2
print(add)

[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]


In [22]:
# Transpose

m1.T

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [23]:
# Dot product
dot=np.dot(m1,m2)
print(dot)

[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


In [31]:
# Multiplication
np.multiply(m1,m2)

matrix([[ 4, 10, 18],
        [28, 40, 54],
        [ 7, 16, 27]])

In [38]:
df=pd.read_excel('https://github.com/IIAnirudhII/BU/blob/master/Deep%20Learning/Lab2/data/Online%20Retail.xlsx?raw=true')
df=df[:100]

In [41]:
arr=df.to_numpy()
arr

array([[536365, '85123A', 'WHITE HANGING HEART T-LIGHT HOLDER', 6,
        Timestamp('2010-12-01 08:26:00'), 2.55, 17850.0,
        'United Kingdom'],
       [536365, 71053, 'WHITE METAL LANTERN', 6,
        Timestamp('2010-12-01 08:26:00'), 3.39, 17850.0,
        'United Kingdom'],
       [536365, '84406B', 'CREAM CUPID HEARTS COAT HANGER', 8,
        Timestamp('2010-12-01 08:26:00'), 2.75, 17850.0,
        'United Kingdom'],
       [536365, '84029G', 'KNITTED UNION FLAG HOT WATER BOTTLE', 6,
        Timestamp('2010-12-01 08:26:00'), 3.39, 17850.0,
        'United Kingdom'],
       [536365, '84029E', 'RED WOOLLY HOTTIE WHITE HEART.', 6,
        Timestamp('2010-12-01 08:26:00'), 3.39, 17850.0,
        'United Kingdom'],
       [536365, 22752, 'SET 7 BABUSHKA NESTING BOXES', 2,
        Timestamp('2010-12-01 08:26:00'), 7.65, 17850.0,
        'United Kingdom'],
       [536365, 21730, 'GLASS STAR FROSTED T-LIGHT HOLDER', 6,
        Timestamp('2010-12-01 08:26:00'), 4.25, 17850.0,
        